#!/bin/bash

## Random {{{
[ -f `which nvim` ] && alias vim='nvim'
alias vi='vim'
alias buspirate='minicom buspirate'
alias rn42='minicom rn42'

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/$\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias tattach='tmux attach-session -t'

function d() {
    expr $((RANDOM%$1)) + 1
}
alias d6='d 6'
alias d20='d 20'
alias broadcast='script -qf | tee >(nc -kl 5000)'
## }}}

## Development {{{
alias make='make -j`expr $NUM_PROCESSORS + 1`'
alias scons='scons -j`expr $NUM_PROCESSORS + 1`'
alias scont='scons -j`expr $NUM_PROCESSORS + 1` -c'
alias klean='make clean && make'
alias cant='ant clean && ant'

gtrack() {
    [ $# -eq 1 ] && {
        server='origin'
        branch=$1
    } || {
        server=$1
        branch=$2
    }
    git branch --set-to-upstream=${remote}/${branch} ${branch}
}
alias gp='git pull'
alias smgp='gp && git submodule foreach --recursive "git pull"'

vrofile() {
    vim --cmd 'profile start /tmp/vim.profile' --cmd 'profile func *' $* && vi /tmp/vim.profile +/SORTED
}
## }}}

## S-based aliases {{{
alias g='s -g'
alias gi='s -g -i'
alias f='s -f'
# alias todo='g "(FIXME|TODO)"'
alias todo='g TODO'
## }}}

## Color aliases {{{
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
alias du='du_color'
## }}}

## Typo fixing {{{
alias emacs='echo "Correcting typos in command..."; sleep 1s; gvim'
alias xemacs='emacs'
alias :q='exit'
alias :qa='exit'
## }}}

# vim: set foldmethod=marker:
