#!/bin/bash

#
# NOTE: any 'chunkc' command that is run from this config file
#       that is NOT 'chunkc core::<..>' or 'chunkc set ..'
#       MUST be put in the background using &


# NOTE: specify the desired level of logging.
#       - none, debug, profile, warn, error
chunkc core::log_level warn
chunkc core::log_file stdout

# NOTE: specify the absolutepath to the directory to use when loading a plugin.
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
chunkc core::hotload 0

# NOTE: the following are config variables for the chunkwm-tiling plugin.
chunkc set custom_bar_enabled            0
chunkc set custom_bar_all_monitors       0
chunkc set custom_bar_offset_top         0
chunkc set custom_bar_offset_bottom      0
chunkc set custom_bar_offset_left        0
chunkc set custom_bar_offset_right       0

chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top     0
chunkc set global_desktop_offset_bottom  0
chunkc set global_desktop_offset_left    0
chunkc set global_desktop_offset_right   0
chunkc set global_desktop_offset_gap     0

# NOTE: desktop-specific settings
chunkc set 1_desktop_mode                monocle

chunkc set desktop_padding_step_size     0.0
chunkc set desktop_gap_step_size         0.0

chunkc set bsp_spawn_left                0
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc set mouse_move_window             none
chunkc set mouse_resize_window           none

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        5
chunkc set preselect_border_radius       0
chunkc set preselect_border_outline      0

# NOTE: these settings require chwm-sa.
chunkc set window_float_topmost          0
chunkc set window_fade_inactive          1
chunkc set window_fade_alpha             0.70
chunkc set window_fade_duration          0.10
chunkc set window_use_cgs_move           0

# specify plugins to load when chunkwm starts.
chunkc core::load tiling.so

# tiling rules
chunkc tiling::rule --owner \"System Preferences\" --subrole AXStandardWindow --state tile &
chunkc tiling::rule --owner \"Key Codes\" --state tile &
chunkc tiling::rule --owner Finder --name Copy --state float &
chunkc tiling::rule --owner \"Google Chrome\" --name \"Meet -\" --monitor 1 --state native-fullscreen --alpha 1 --follow-desktop &
chunkc tiling::rule --owner \"Cisco WebEx Meeting Center\" --name \"Cisco Webex Meetings\" --monitor 1 --alpha 1 --follow-desktop &
chunkc tiling::rule --owner Slack --name \"Slack call\" --monitor 1 --alpha 1 --follow-desktop  &
chunkc tiling::rule --owner zoom.us --name \"Zoom Meeting\" --monitor 1 --alpha 1 --follow-desktop  &
chunkc tiling::rule --owner join.me --monitor 1 --alpha 1 --follow-desktop  &
