#!/usr/bin/env sh

# global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config status_bar                   off
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.10
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.70
# yabai -m config split_ratio                  0.50
# yabai -m config auto_balance                 off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# tiling rules
# yabai -m rule --add app=\"System Preferences\" manage=true
# yabai -m rule --add app=\"Key Codes\" manage=true
# yabai -m rule --add app=Finder title=Copy manage=false
# yabai -m rule --add app=\"Google Chrome\" title=\"Meet -\" display=^1 native-fullscreen=true opacity=1
# yabai -m rule --add app=\"Cisco WebEx Meeting Center\" title=\"Cisco Webex Meetings\" display=^1 opacity=1
# yabai -m rule --add app=Slack title=\"Slack call\" display=^1 opacity=1
# yabai -m rule --add app=zoom.us title=\"Zoom Meeting\" display=^1 opacity=1
# yabai -m rule --add app=join.me display=^1 opacity=1

echo "yabai configuration loaded.."
